# Generated by Django 3.1.6 on 2021-04-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dlprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
