# Generated by Django 3.1.6 on 2021-04-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0004_auto_20210403_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.FileField(default=0, upload_to='previews/'),
            preserve_default=False,
        ),
    ]
