# Generated by Django 3.1.6 on 2021-04-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0005_product_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aboutauthor',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
    ]
